name: 'Node 12 Template Action'
description: 'Get started with Node actions'
author: '8398a7'
inputs:
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'node12'
  main: 'lib/main.js'
