name: action-slack
description: You can notify slack of GitHub Actions.
author: 8398a7
inputs:
  type:
    description: success or failed
  payload:
    description: 'json payload(refs: https://github.com/slackapi/node-slack-sdk/blob/v5.0.0/packages/webhook/src/IncomingWebhook.ts#L91-L106)'
runs:
  using: node12
  main: lib/main.js
