name: Slack Pre
on:
  push:
    branches:
      - pre

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Succeeded
        uses: 8398a7/action-slack@pre
        with:
          status: Success
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_FOR_INTEGRATION_TEST }}
      - name: Failed
        uses: 8398a7/action-slack@pre
        with:
          status: Failure
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_FOR_INTEGRATION_TEST }}
      - name: Canceled
        uses: 8398a7/action-slack@pre
        with:
          status: Cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_FOR_INTEGRATION_TEST }}
      - name: Legacy Webhook URL
        uses: 8398a7/action-slack@pre
        with:
          status: ${{ job.status }}
          username: legacy user
          icon_emoji: ":octocat:"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_LEGACY_WEBHOOK_URL_FOR_INTEGRATION_TEST }}
      - name: Custom Field
        uses: 8398a7/action-slack@pre
        with:
          status: custom
          custom_payload: |
            {
              text: "Custom Field Check",
              attachments: [{
                "author_name": "8398a7@action-slack", // json
                fallback: 'fallback',
                color: 'good',
                title: 'CI Result',
                text: 'Succeeded',
                fields: [{
                  title: 'lower case',
                  value: 'LOWER CASE CHECK'.toLowerCase(),
                  short: true
                },
                {
                  title: 'reverse',
                  value: 'gnirts esrever'.split('').reverse().join(''),
                  short: true
                },
                {
                  title: 'long title1',
                  value: 'long value1',
                  short: false
                }],
                actions: [{
                }]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_FOR_INTEGRATION_TEST }}
      - name: Custom Field2
        uses: 8398a7/action-slack@pre
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              username: 'action-slack',
              icon_emoji: ':octocat:',
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_LEGACY_WEBHOOK_URL_FOR_INTEGRATION_TEST }}
      - name: if_mention
        uses: 8398a7/action-slack@pre
        with:
          status: ${{ job.status }}
          mention: here
          if_mention: always
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_FOR_INTEGRATION_TEST }}
      - name: Fields Check
        uses: 8398a7/action-slack@pre
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,job,eventName,ref,workflow,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_FOR_INTEGRATION_TEST }}
      - uses: 8398a7/action-slack@pre
        with:
          status: ${{ job.status }}
          fields: repo,message,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  matrix-notification:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: 8398a7/action-slack@pre
        with:
          status: ${{ job.status }}
          fields: job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_FOR_INTEGRATION_TEST }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        if: always()
