name: Slack Checks
on:
  push:
    branches:
    - v0

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Full Field Check
      uses: 8398a7/action-slack@v0
      with:
        text: Full Field Check
        attachments: |
          [{
            "author_name": "slack-actions",
            "fallback": "fallback",
            "color": "good",
            "title": "CI Result",
            "text": "Succeeded",
            "fields": [{
              "title": "short title1",
              "value": "short value1",
              "short": true
            },
            {
              "title": "short title2",
              "value": "short value2",
              "short": true
            },
            {
              "title": "long title1",
              "value": "long value1",
              "short": false
            }],
            "actions": [{
            }]
          }]
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    - name: Succeeded Check
      uses: 8398a7/action-slack@v0
      with:
        type: success
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    - name: Failed Check
      uses: 8398a7/action-slack@v0
      with:
        type: failed
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
