name: Slack Checks
on:
  push:
    branches:
    - v0

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: 8398a7/action-slack@v0
      with:
        text: Succeeded slack checks
        attachment.color: '#439FE0'
        attachment.title: check slack
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
