name: Slack Pre
on:
  push:
    branches:
      - pre

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Succeeded Check
        uses: 8398a7/action-slack@pre
        with:
          status: Success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Failed Check
        uses: 8398a7/action-slack@pre
        with:
          status: fail
          only_mention_fail: here
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Canceled Check
        uses: 8398a7/action-slack@pre
        with:
          status: cancelled
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Custom Field Check
        uses: 8398a7/action-slack@pre
        with:
          status: custom
          payload: |
            {
              "text": "Custom Field Check",
              "attachments": [{
                "author_name": "slack-actions",
                "fallback": "fallback",
                "color": "good",
                "title": "CI Result",
                "text": "Succeeded",
                "fields": [{
                  "title": "short title1",
                  "value": "short value1",
                  "short": true
                },
                {
                  "title": "short title2",
                  "value": "short value2",
                  "short": true
                },
                {
                  "title": "long title1",
                  "value": "long value1",
                  "short": false
                }],
                "actions": [{
                }]
              }]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Check
        uses: 8398a7/action-slack@pre
        with:
          status: ${{ job.status }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
