name: Slack Checks
on:
  push:
    branches:
    - v0

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: 8398a7/action-slack@v0
      with:
        text: Succeeded slack checks
        attachments: |
          [{
            "author_name": "",
            "fallback": "",
            "color": "",
            "title": "",
            "text": "",
            "fields": [{
              "title": "short title1",
              "value": "short value1",
              "short": true
            },
            {
              "title": "short title2",
              "value": "short value2",
              "short": true
            },
            {
              "title": "long title1",
              "value": "long value1",
              "short": false
            }]
          }]
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
